owner: petebachant
name: clima-coupled-land-slowdown
title: CliMA coupled land slowdown
description: Investigating why a CliMA coupled simulation is disproportionately
  slower with the integrated land model versus a bucket model.
git_repo_url: https://github.com/petebachant/clima-coupled-land-slowdown

questions:
  - Why is the AMIP coupled config so much slower when using the integrated
    land model versus the bucket model?

environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu

pipeline:
  # TODO: Add stage templates feature to reduce duplication
  # stage_templates:
  #   nsys:
  #     template:
  #       kind: sbatch
  #       environment: clima
  #       script_path: scripts/run-nsys.sh
  #       sbatch_options:
  #         - --gpus=1
  #         - --time=30
  #       args:
  #         - "results/nsys/{case_name}"
  #         - "{project_dir}"
  #         - "{config_yaml_fpath}"
  #       inputs:
  #         - scripts/run.jl
  #         - ClimaCoupler.jl/src
  #         - "{project_dir}/Manifest-v1.11.toml"
  #         - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
  #       outputs:
  #         - "results/nsys/{case_name}.nsys-rep"
  #     inputs:
  #       case_name: str
  #       project_dir: str
  #       config_yaml_fpath: str
  stages:
    baseline-bucket-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/baseline-bucket # Output
        - ClimaCoupler.jl/experiments/ClimaEarth # Project folder
        - ClimaCoupler.jl/config/longrun_configs/amip_edonly.yml # Config
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl/src
        - ClimaCoupler.jl/config/longrun_configs/amip_edonly.yml
        - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
      outputs:
        - results/nsys/baseline-bucket.nsys-rep
    baseline-integrated-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/baseline-integrated # Output
        - ClimaCoupler.jl/experiments/ClimaEarth # Project folder
        - ClimaCoupler.jl/config/longrun_configs/amip_edonly_integrated_land.yml # Config
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl/src
        - ClimaCoupler.jl/config/longrun_configs/amip_edonly_integrated_land.yml
        - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
      outputs:
        - results/nsys/baseline-integrated.nsys-rep
    mod-bucket-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/mod-bucket # Output
        - ClimaCoupler.jl-mod/experiments/ClimaEarth # Project folder
        - ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly.yml # Config
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl-mod/src
        - ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly.yml
        - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
      outputs:
        - results/nsys/mod-bucket.nsys-rep
    mod-integrated-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/mod-integrated # Output
        - ClimaCoupler.jl-mod/experiments/ClimaEarth # Project folder
        - ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly_integrated_land.yml # Config
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl-mod/src
        - ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly_integrated_land.yml
        - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
      outputs:
        - results/nsys/mod-integrated.nsys-rep
    height-z-integrated-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/height-z-integrated # Output
        - ClimaCoupler.jl-height-z/experiments/ClimaEarth # Project folder
        - ClimaCoupler.jl-height-z/config/longrun_configs/amip_edonly_integrated_land.yml # Config
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl-height-z/src
        - ClimaCoupler.jl-height-z/config/longrun_configs/amip_edonly_integrated_land.yml
        - ClimaCoupler.jl-height-z/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl-height-z/experiments/ClimaEarth/setup_run.jl
      outputs:
        - results/nsys/height-z-integrated.nsys-rep
    imp-fluxes-integrated-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/imp-fluxes-integrated # Output
        - ClimaCoupler.jl-imp-fluxes/experiments/ClimaEarth # Project folder
        - ClimaCoupler.jl-imp-fluxes/config/longrun_configs/amip_edonly_integrated_land.yml # Config
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl-imp-fluxes/src
        - ClimaCoupler.jl-imp-fluxes/config/longrun_configs/amip_edonly_integrated_land.yml
        - ClimaCoupler.jl-imp-fluxes/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl-imp-fluxes/experiments/ClimaEarth/setup_run.jl
      outputs:
        - results/nsys/imp-fluxes-integrated.nsys-rep
    # amip-clima-ncu:
    #   kind: sbatch
    #   environment: clima
    #   script_path: scripts/run-ncu-clima.sh
    #   sbatch_options:
    #     - --gpus=1
    #     - --time=240
    #   args:
    #     - ncu-outputs/amip-target-edonly-63
    #     - --config ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
    #     - --config config/amip_target_edonly.yml
    #     - --kernel-name copyto_stencil_kernel_
    #     - --launch-skip 0
    #     - --launch-count 20
    #   inputs:
    #     - ClimaAtmos.jl/perf/benchmark_step.jl
    #     - ClimaAtmos.jl/config/default_configs/default_config.yml
    #     - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
    #     - config/amip_target_edonly.yml
    #     - ClimaAtmos.jl/toml/longrun_aquaplanet.toml
    #     - ClimaAtmos.jl/src
    #     - ClimaCore.jl/src
    #     - Manifest.toml
    #   outputs:
    #     - ncu-outputs/amip-target-edonly-63.ncu-rep
