stages:
  baseline-bucket-nsys:
    cmd: calkit slurm batch --name baseline-bucket-nsys --environment 
      clima --dep scripts/run.jl --dep ClimaCoupler.jl/src --dep 
      ClimaCoupler.jl/config/longrun_configs/amip_edonly.yml --dep 
      ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml --dep
      ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl --out 
      results/nsys/baseline-bucket.nsys-rep -s --gpus=1 -s --time=60 
      -- scripts/run-nsys.sh results/nsys/baseline-bucket 
      ClimaCoupler.jl/experiments/ClimaEarth 
      ClimaCoupler.jl/config/longrun_configs/amip_edonly.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl/src
      - ClimaCoupler.jl/config/longrun_configs/amip_edonly.yml
      - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
    outs:
      - results/nsys/baseline-bucket.nsys-rep:
          persist: true
    desc: Automatically generated from the 'baseline-bucket-nsys' 
      stage in calkit.yaml. Changes made here will be overwritten.
  baseline-integrated-nsys:
    cmd: calkit slurm batch --name baseline-integrated-nsys 
      --environment clima --dep scripts/run.jl --dep 
      ClimaCoupler.jl/src --dep 
      ClimaCoupler.jl/config/longrun_configs/amip_edonly_integrated_land.yml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl --out 
      results/nsys/baseline-integrated.nsys-rep -s --gpus=1 -s 
      --time=60 -- scripts/run-nsys.sh 
      results/nsys/baseline-integrated 
      ClimaCoupler.jl/experiments/ClimaEarth 
      ClimaCoupler.jl/config/longrun_configs/amip_edonly_integrated_land.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl/src
      - ClimaCoupler.jl/config/longrun_configs/amip_edonly_integrated_land.yml
      - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
    outs:
      - results/nsys/baseline-integrated.nsys-rep:
          persist: true
    desc: Automatically generated from the 'baseline-integrated-nsys' 
      stage in calkit.yaml. Changes made here will be overwritten.
  mod-bucket-nsys:
    cmd: calkit slurm batch --name mod-bucket-nsys --environment clima
      --dep scripts/run.jl --dep ClimaCoupler.jl-mod/src --dep 
      ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly.yml --dep
      ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl 
      --out results/nsys/mod-bucket.nsys-rep -s --gpus=1 -s --time=60 
      -- scripts/run-nsys.sh results/nsys/mod-bucket 
      ClimaCoupler.jl-mod/experiments/ClimaEarth 
      ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl-mod/src
      - ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly.yml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
    outs:
      - results/nsys/mod-bucket.nsys-rep:
          persist: true
    desc: Automatically generated from the 'mod-bucket-nsys' stage in 
      calkit.yaml. Changes made here will be overwritten.
  mod-integrated-nsys:
    cmd: calkit slurm batch --name mod-integrated-nsys --environment 
      clima --dep scripts/run.jl --dep ClimaCoupler.jl-mod/src --dep 
      ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly_integrated_land.yml
      --dep 
      ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl 
      --out results/nsys/mod-integrated.nsys-rep -s --gpus=1 -s 
      --time=60 -- scripts/run-nsys.sh results/nsys/mod-integrated 
      ClimaCoupler.jl-mod/experiments/ClimaEarth 
      ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly_integrated_land.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl-mod/src
      - ClimaCoupler.jl-mod/config/longrun_configs/amip_edonly_integrated_land.yml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
    outs:
      - results/nsys/mod-integrated.nsys-rep:
          persist: true
    desc: Automatically generated from the 'mod-integrated-nsys' stage
      in calkit.yaml. Changes made here will be overwritten.
  height-z-integrated-nsys:
    cmd: calkit slurm batch --name height-z-integrated-nsys 
      --environment clima --dep scripts/run.jl --dep 
      ClimaCoupler.jl-height-z/src --dep 
      ClimaCoupler.jl-height-z/config/longrun_configs/amip_edonly_integrated_land.yml
      --dep 
      ClimaCoupler.jl-height-z/experiments/ClimaEarth/Manifest-v1.11.toml
      --dep 
      ClimaCoupler.jl-height-z/experiments/ClimaEarth/setup_run.jl 
      --out results/nsys/height-z-integrated.nsys-rep -s --gpus=1 -s 
      --time=60 -- scripts/run-nsys.sh 
      results/nsys/height-z-integrated 
      ClimaCoupler.jl-height-z/experiments/ClimaEarth 
      ClimaCoupler.jl-height-z/config/longrun_configs/amip_edonly_integrated_land.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl-height-z/src
      - ClimaCoupler.jl-height-z/config/longrun_configs/amip_edonly_integrated_land.yml
      - ClimaCoupler.jl-height-z/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl-height-z/experiments/ClimaEarth/setup_run.jl
    outs:
      - results/nsys/height-z-integrated.nsys-rep:
          persist: true
    desc: Automatically generated from the 'height-z-integrated-nsys' 
      stage in calkit.yaml. Changes made here will be overwritten.
  imp-fluxes-integrated-nsys:
    cmd: calkit slurm batch --name imp-fluxes-integrated-nsys 
      --environment clima --dep scripts/run.jl --dep 
      ClimaCoupler.jl-imp-fluxes/src --dep 
      ClimaCoupler.jl-imp-fluxes/config/longrun_configs/amip_edonly_integrated_land.yml
      --dep 
      ClimaCoupler.jl-imp-fluxes/experiments/ClimaEarth/Manifest-v1.11.toml
      --dep 
      ClimaCoupler.jl-imp-fluxes/experiments/ClimaEarth/setup_run.jl 
      --out results/nsys/imp-fluxes-integrated.nsys-rep -s --gpus=1 -s
      --time=60 -- scripts/run-nsys.sh 
      results/nsys/imp-fluxes-integrated 
      ClimaCoupler.jl-imp-fluxes/experiments/ClimaEarth 
      ClimaCoupler.jl-imp-fluxes/config/longrun_configs/amip_edonly_integrated_land.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl-imp-fluxes/src
      - ClimaCoupler.jl-imp-fluxes/config/longrun_configs/amip_edonly_integrated_land.yml
      - ClimaCoupler.jl-imp-fluxes/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl-imp-fluxes/experiments/ClimaEarth/setup_run.jl
    outs:
      - results/nsys/imp-fluxes-integrated.nsys-rep:
          persist: true
    desc: Automatically generated from the 
      'imp-fluxes-integrated-nsys' stage in calkit.yaml. Changes made 
      here will be overwritten.
